version: "2"
services:
  db:
    build: ./db/
    environment:
      POSTGRES_USER: "verftech"
      POSTGRES_PASSWORD: "verftech"
#    ports:
#      - "5432:5432"
  web:
    build: ./app/
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/verftech?user=verftech&password=verftech"
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

